apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: northamerica-northeast1-docker.pkg.dev/k8s-assignment-402302/cloud-computing/app1:5.0
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: /Dev_PV_dir
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc

---

apiVersion : v1
kind : Service
metadata : 
  name: app1-service
  namespace : assignment
spec : 
  type: LoadBalancer
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000