apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: northamerica-northeast1-docker.pkg.dev/k8s-assignment-402302/cloud-computing/app2:5.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /Dev_PV_dir
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc

---

apiVersion : v1
kind : Service
metadata : 
  name: app2-service
  namespace : assignment
spec : 
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000